AdminRole/Controllers/BugsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AdminRole.Models;
using Microsoft.AspNet.Identity;

namespace AdminRole.Controllers
{

    public class BugsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Bugs
        public ActionResult Index()
        {
            return View(db.Bugs.ToList());
        }

        public ActionResult MyProjects()
        {
            string userId = User.Identity.GetUserId();
            var UsersIds = db.Users.Where(p => p.Id == userId).FirstOrDefault();
            var bugs = UsersIds.Bugs.ToList();
            return View("Index", bugs);
        }

        // GET: Bugs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bug bug = db.Bugs.Find(id);
            if (bug == null)
            {
                return HttpNotFound();
            }
            return View(bug);
        }

        // GET: Bugs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Bugs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name")] Bug bug)
        {
            if (ModelState.IsValid)
            {
                db.Bugs.Add(bug);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(bug);
        }

        // GET: Bugs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bug bug = db.Bugs.Find(id);
            if (bug == null)
            {
                return HttpNotFound();
            }
            return View(bug);
        }

        // POST: Bugs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] Bug bug)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bug).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bug);
        }

        // GET: Bugs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bug bug = db.Bugs.Find(id);
            if (bug == null)
            {
                return HttpNotFound();
            }
            return View(bug);
        }

        // POST: Bugs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Bug bug = db.Bugs.Find(id);
            db.Bugs.Remove(bug);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult AssignUsers(int id)
        {
            var model = new ProjectAssignViewModel();
            model.Id = id;
            var bug = db.Bugs.FirstOrDefault(p => p.Id == id);
            var users = db.Users.ToList();
            var userIdsAssignedToProject = bug.Users
                .Select(p => p.Id).ToList();
            model.UserList = new MultiSelectList(users, "Id", "Name", userIdsAssignedToProject);
            return View(model);
        }

        [HttpPost]
        public ActionResult AssignUsers(ProjectAssignViewModel model)
        {
            //STEP 1: Find the project
            var bug = db.Bugs.FirstOrDefault(p => p.Id == model.Id);
            //STEP 2: Remove all assigned users from this project
            var assignedUsers = bug.Users.ToList();
            foreach (var user in assignedUsers)
            {
                bug.Users.Remove(user);
            }
            //STEP 3: Assign users to the project
            if (model.SelectedUsers != null)
            {
                foreach (var userId in model.SelectedUsers)
                {
                    var user = db.Users.FirstOrDefault(p => p.Id == userId);
                    bug.Users.Add(user);
                }
            }
            //STEP 4: Save changes to the database
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AdminRole/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin - Bootstrap Admin Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

    <!-- Custom CSS -->
    <link href="~/Content/sb-admin.css" rel="stylesheet" />

    <!-- Custom Fonts -->
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/plugins/morris.css" rel="stylesheet" />
    <link href="http://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" />

</head>
<body>
    <div id="wrapper">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand">Bug Tracker</a>
            </div>
            <!-- Top Menu Items -->
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li class="active">
                        <a href="@Url.Action("Index","Home")"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
                    </li>
                    <li>
                        @Html.Partial("_LoginPartial")
                    </li>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo"><i class="fa fa-fw fa-arrows-v"></i> Roles <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo" class="collapse">
                            @if (User.IsInRole("Admin"))
                            {
                                <li>
                                    <a href="@Url.Action("Index","ApplicationUsers")"><i class="fa fa-fw fa-file"></i> ChangeRoles</a>
                                </li>
                            }
                        </ul>
                    </li>

                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo1"><i class="fa fa-fw fa-arrows-v"></i> projects <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo1" class="collapse">
                            @if (User.IsInRole("Admin") || User.IsInRole("Project Manager"))
                            {
                                <li>
                                    <a href="@Url.Action("Index", "Bugs", "Bugs")"><i class="fa fa-fw fa-file"></i> Exercises</a>
                                </li>
                            }
                        </ul>
                    </li>

                    <li>

                        @if (User.IsInRole("Submitter"))
                        {
                            <a href="javascript:;" data-toggle="collapse" data-target="#demo2"><i class="fa fa-fw fa-arrows-v"></i> Tickets <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo2" class="collapse">
                            
                            <li>
                                <a href="@Url.Action("Index", "Tickets", new { id = "" })" class=" hvr-bounce-to-right"> <i class="fa fa-info-circle nav_icon"></i>All Tickets</a>
                                <a href="@Url.Action("UserTickets", "Tickets", new { id = "User" })" class=" hvr-bounce-to-right"> <i class="fa fa-info-circle nav_icon"></i>Own Tickets</a>
                            </li>
                        </ul>
                        }
                    </li>

                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo3"><i class="fa fa-fw fa-arrows-v"></i> Demo Users Login<i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo3" class="collapse">
                            <li>
                            <a href="@Url.Action("DemoUsersLogin", "Account", new { name = "Admin"})">Admin</a>
                            <a href="@Url.Action("DemoUsersLogin", "Account", new { name = "Project Manager"})">Project manager</a>
                            <a href="@Url.Action("DemoUsersLogin", "Account", new { name = "Developer"})">Developer</a>
                            <a href="@Url.Action("DemoUsersLogin", "Account", new { name = "Submitter"})">Submitter</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>
        <div id="page-wrapper">
            <div class="container-fluid">
                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            Dashboard
                        </h1>
                    </div>
                </div>
                @RenderBody()
            </div>
        </div>
    </div>
    <!-- jQuery -->
    <script src="~/Scripts/jquery.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="~/Scripts/bootstrap.min.js"></script>
    @*<script src="~/Scripts/plugins/morris/raphael.min.js"></script>
    <script src="~/Scripts/plugins/morris/morris.min.js"></script>
    <script src="~/Scripts/plugins/morris/morris-data.js"></script>*@
    <script type="text/javascript" src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

    @RenderSection("Scripts", false)

</body>
</html>